name: Output Event Details on Issues
on:
  issues:
    types: opened
      jobs:
        info:
          runs-on: ubuntu-latest
          steps:
            - name: Output Issue context
              run: echo "${{ toJSON(github) }}"